server:
  port: 8888
  servlet:
    context-path: /

limit:
  minMoney: 2
  maxMoney: 100
  desc: 最低${limit.minMoney}最高${limit.maxMoney}


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.95.119.164:3306/scott
      username: fy2019
      #password: Qinfo20180507@
      password: ENC(/SLRrFpIUt6VVTJjKVA36MDgo+Iz3+UO)
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

jasypt:
  encryptor:
    password: test