server:
  port: 8888
  servlet:
    context-path: /


limit:
  minMoney: 2
  maxMoney: 100
  desc: 最低${limit.minMoney}最高${limit.maxMoney}



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.95.119.164:3306/business
      username: fy2019
      password: Qinfo20180507@
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    com.neuedu.dao: debug

### 配置redis连接池参数
redis:
  max:
    total: 8
    idle: 8
  min:
    idle: 2
  test:
    borrow: true
    return: true
  ip: 47.95.119.164
  port: 5379
  password: Qinfo20180507@
  timeout: 2000

# redis.conf 1.port 2.bind 0.0.0.0 3.requirepass newpassword

order:
  close:
    timeout: 2

lock:
  timeout: 20000




